###user api req
###
post http://localhost:5000/user-api/login
Content-Type: application/json

{
    "userType":"user",
    "username":"Aashritha",
    "password":"Aash"
}

###
post http://localhost:5000/user-api/getusertype
Content-Type: application/json

{
    "username":"Aashritha"
}

###
get http://localhost:5000/alumini-api/form
###
post http://localhost:5000/admin-api/login
Content-Type: application/json

{
    "userType":"admin",
    "username":"Aash",
    "password":"Aash"
}
###

post http://localhost:5000/admin-api/adduser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFhc2giLCJpYXQiOjE3MTc1ODMxMTEsImV4cCI6MTcxNzY2OTUxMX0.gWhcDdVd6gYaBEjSRF_luyQ7H5k1JyAGEo_bM1mN9rE
Content-Type: application/json

{
    "username":"Arjun",
    "userType2":"alumni",
    "email":"abca@gmail.com"
}

###
put http://localhost:5000/admin-api/updateuser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFhc2giLCJpYXQiOjE3MTc1MzEwODEsImV4cCI6MTcxNzYxNzQ4MX0._RqkRw8SU_Tlz1wxOGieo-94qF7iLDaXdIIXAqfQyN0
Content-Type: application/json

{
   "username":"Aashritha",
    "password":"Aash",
    "userType2":"alumni",
    "email":"aashritha1@gmail.com" 
}

###
post http://localhost:5000/admin-api/retrieveuser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFhc2giLCJpYXQiOjE3MTc1MzEwODEsImV4cCI6MTcxNzYxNzQ4MX0._RqkRw8SU_Tlz1wxOGieo-94qF7iLDaXdIIXAqfQyN0
Content-Type: application/json

{
   "username":"Aashritha"
}

###
put http://localhost:5000/admin-api/deleteuser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFhc2giLCJpYXQiOjE3MTc1MzEwODEsImV4cCI6MTcxNzYxNzQ4MX0._RqkRw8SU_Tlz1wxOGieo-94qF7iLDaXdIIXAqfQyN0
Content-Type: application/json

{
   "username":"Aashritha"
}

###
get http://localhost:5000/aa1/testit
###reading articles of all users

