POST http://localhost:4000/admin-api/create-user
Content-Type: application/json

{
    "name":"",
    "usertype":"admin",
    "emailID":"xxx"
}

###
POST http://localhost:4000/admin-api/login
Content-Type: application/json

{
    "username":"xxx",
    "password":"xxx"
}